# Workflow
name: Hello

# On teels when the workflow should run
on:
  workflow_dispatch:

# Job tells what the workflow should do, there can be one or more than one jobs, hence we write jobs
# jobs is an object so needs indentation
jobs:
  # 1st job(give indentation)
  say-hello:
    # Create an Ephermal container with ubuntu running 
    runs-on: ubuntu-latest
    # That ephermal container will have steps to execute, hence name those steps and use run: run has the commond
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
